name: 04 Using Workflow Actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7
    - name: "Print Folders"
      run: |
        echo "Printing the folders in the repository:"
        ls -R
